#!/usr/bin/env ruby

require 'erb'

def path_to_template name
  File.join Dir.pwd, "script/templates/#{name}.erb"
end

def with_template name
  template_content = File.read path_to_template(name)
  template = ERB.new template_content, 0, "%<>"
  yield template
end

html_template = ERB.new <<EOF, 0, "%<>" 
<html>
<head>
</head>
<body>
% simple_elements.each do |element|
  <<%= element %>><%= element %> unexpected content</<%= element %>>
  <<%= element %> id="<%= element %>_identifier"><%= element %> expected content</<%= element %>>
% end
</body>
</html>
EOF

simple_elements = []
simple_elements += (1..6).map{|i| "h#{i}"}
simple_elements += %w{div}
simple_elements += %w{span}
simple_elements += %w{p}
# simple_elements += %w{i strong}

File.open 'features/support/test.html', 'w' do |f|
  f.puts html_template.result(binding)
end

with_template 'feature' do |feature_template|
  simple_elements.each do |element|
    File.open "features/simple_elements/#{element}.feature", 'w' do |f|
      f.puts feature_template.result(binding)
    end
  end
end