#!/usr/bin/env ruby

require 'erb'

def path_to_template name
  File.join Dir.pwd, "script/templates/#{name}.erb"
end

def with_template name
  template_content = File.read path_to_template(name)
  template = ERB.new template_content, 0, "%<>"
  yield template
end

simple_elements = []
simple_elements += (1..6).map{|i| "h#{i}"}
simple_elements += %w{div span p}

with_template 'test.html' do |html_template|
  File.open 'features/support/test.html', 'w' do |f|
    f.puts html_template.result(binding)
  end
end

with_template 'feature' do |feature_template|
  simple_elements.each do |element|
    File.open "features/simple_elements/#{element}.feature", 'w' do |f|
      f.puts feature_template.result(binding)
    end
  end
end